apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: demo.thepipelineguys.live
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - manifests/
              - values.yml
          - kbld:
              paths:
              - '-'
              - config.yml
      export:
      - imgpkgBundle:
          image: ghcr.io/manuelcoppotelli/demo/package
          useKbldImagesLock: true
        includePaths:
        - manifests/
        - values.yml
